using Test
using Random
using Statistics
using Distributions
using DataFrames
using CSV
using Graphs
using Dates

function snapshot(initial_seed, simulation_seed, output_dir)
    # Match the control-frame schema generated by dataGen2.jl.
    control = DataFrame(dateTime=DateTime(2026, 1, 1), seed1=initial_seed,
        seed2=simulation_seed, key="seed-test", privacyVal=1.0,
        searchResolution=0.05, switchPct=0.05, agtCnt=10,
        pctConnected=0.2, expDegree=2, β=0.5, searchQty=100,
        modRun=0, order=0, initialized=false, duckTick=-10,
        vpnTick=-10, deletionTick=-10, sharingTick=-10)
    # Match mainSweep's include order and isolate each run like a fresh worker.
    model = Module(gensym(:SeedScenario))
    Core.eval(model, :(using Random, Statistics, Distributions, DataFrames, CSV, Graphs))
    Core.eval(model, :(paramVec = $(control[1, :])))
    Base.include(model, joinpath(@__DIR__, "..", "pathConfig.jl"))
    Core.eval(model, :(modelPaths = prepareModelPaths(resolveModelPaths(
        dataDir=$(joinpath(output_dir, "results")), controlFile=$(joinpath(output_dir, "ctrl.jld2"))))))
    for file in ("parameterSet2.jl", "objects2.jl", "initFunctions.jl")
        Base.include(model, joinpath(@__DIR__, "..", file))
    end
    Core.eval(model, :(googleGen()))
    Base.include(model, joinpath(@__DIR__, "..", "agentGen.jl"))
    population = Core.eval(model, :([(a.privacy, params(a.betaObj), params(a.gammaObj),
        a.expUnif, a.expSubj, a.blissPoint) for a in agtList]))
    network = collect(edges(model.agtGraph))

    # Execute the real simulation reseed, with zero ticks to avoid a full run.
    Base.include(model, joinpath(@__DIR__, "..", "modelMain.jl"))
    return (initial_seed=model.seed1, simulation_seed=model.seed2, population=population,
        network=network, simulation_draws=rand(10))
end

@testset "Initialization and simulation use separate control seeds" begin
    mktempdir() do temp_dir
        cd(temp_dir) do
            baseline = snapshot(1234, 5678, temp_dir)
            different_simulation = snapshot(1234, 9876, temp_dir)
            different_population = snapshot(4321, 5678, temp_dir)
            repeated = snapshot(1234, 5678, temp_dir)

            @test baseline.initial_seed == 1234
            @test baseline.simulation_seed == 5678
            @test different_simulation.simulation_seed == 9876
            @test baseline.population == different_simulation.population
            @test baseline.network == different_simulation.network
            @test baseline.simulation_draws != different_simulation.simulation_draws
            @test different_population.initial_seed == 4321
            @test baseline.population != different_population.population
            @test baseline.network != different_population.network
            @test baseline.simulation_draws == different_population.simulation_draws
            @test baseline == repeated
        end
    end
end
