/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -p 8 mainSweep.jl
