/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl
/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia -p 16 mainSweep.jl